### ISSUE TITLE
Gedit 46.0 compatibility

### ISSUE THREAD

**Issue by yochananmarqos** [jefferyto/gedit-ex-mortis#9]
It was working fine with Gedit <=45.0, but now with 46.0 it no longer works:

```
Traceback (most recent call last):
  File "/home/yochanan/.local/share/gedit/plugins/ex-mortis/__init__.py", line 330, in on_app_window_added
    self.setup_window(window)
  File "/home/yochanan/.local/share/gedit/plugins/ex-mortis/__init__.py", line 224, in setup_window
    window_manager.track_window(window)
  File "/home/yochanan/.local/share/gedit/plugins/ex-mortis/windowmanager.py", line 94, in track_window
    state.save_window(window)
  File "/home/yochanan/.local/share/gedit/plugins/ex-mortis/windowstate.py", line 167, in save_window
    self.save_side_panel_page_name(window)
  File "/home/yochanan/.local/share/gedit/plugins/ex-mortis/windowstate.py", line 669, in save_side_panel_page_name
    page_name = side_panel.get_visible_child_name()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PanelContainer' object has no attribute 'get_visible_child_name'
```

**Comment by jefferyto** [comment]
Thanks for opening this (and apologies for the delay) - this should be fixed in the new version (0.2.2).

**Comment by yochananmarqos** [comment]
Yes, thank you!
